/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RegistryFactoryInterface extends utils.Interface {
  contractName: "RegistryFactory";
  functions: {
    "contractAddress(bytes32)": FunctionFragment;
    "create(string,string,address[],string[],bytes32)": FunctionFragment;
    "mrCounter()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "contractAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "create",
    values: [string, string, string[], string[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "mrCounter", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "contractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mrCounter", data: BytesLike): Result;

  events: {
    "RegistryCreated(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RegistryCreated"): EventFragment;
}

export type RegistryCreatedEvent = TypedEvent<
  [string, string, BigNumber],
  { creator: string; newRegistry: string; number: BigNumber }
>;

export type RegistryCreatedEventFilter = TypedEventFilter<RegistryCreatedEvent>;

export interface RegistryFactory extends BaseContract {
  contractName: "RegistryFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegistryFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    contractAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    create(
      __symbol: string,
      __name: string,
      addresses: string[],
      foundersCids: string[],
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mrCounter(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  contractAddress(salt: BytesLike, overrides?: CallOverrides): Promise<string>;

  create(
    __symbol: string,
    __name: string,
    addresses: string[],
    foundersCids: string[],
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mrCounter(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    contractAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    create(
      __symbol: string,
      __name: string,
      addresses: string[],
      foundersCids: string[],
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    mrCounter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "RegistryCreated(address,address,uint256)"(
      creator?: null,
      newRegistry?: null,
      number?: BigNumberish | null
    ): RegistryCreatedEventFilter;
    RegistryCreated(
      creator?: null,
      newRegistry?: null,
      number?: BigNumberish | null
    ): RegistryCreatedEventFilter;
  };

  estimateGas: {
    contractAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    create(
      __symbol: string,
      __name: string,
      addresses: string[],
      foundersCids: string[],
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mrCounter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    contractAddress(
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    create(
      __symbol: string,
      __name: string,
      addresses: string[],
      foundersCids: string[],
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mrCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
